"""FxSocket Python SDK.

Account management today (the v1 API); per-account terminal REST and
WebSocket streaming for MT4/MT5 land in the next milestones.
"""

from __future__ import annotations

from . import errors
from ._version import __version__
from .client import AsyncClient, Client
from .enums import (
    DealEntry,
    HealthStatus,
    OrderKind,
    OrderOperation,
    Platform,
    Timeframe,
    TradingStatus,
)
from .errors import (
    AccountCapError,
    AuthError,
    ConnectFailedError,
    DuplicateAccountError,
    FxSocketError,
    NoSubscriptionError,
    NotFoundError,
    RateLimitError,
    StreamError,
    TerminalNotReadyError,
    TerminalTimeoutError,
    UnsupportedOnPlatformError,
    ValidationError,
)
from .models import (
    Account,
    AccountInfo,
    AccountSummary,
    Candle,
    Health,
    HealthChecks,
    HistoryTrade,
    MarginCalc,
    OpenedOrder,
    OrderResult,
    PositionTrade,
    ProfitCalc,
    Quote,
    ServerTimezone,
    SymbolInfo,
    TerminalStatusData,
    TradeEventData,
)
from .terminal import (
    AccountUpdate,
    AsyncStream,
    AsyncTerminalClient,
    Bar,
    PositionsUpdate,
    Stream,
    StreamErrorEvent,
    StreamEvent,
    StreamWarning,
    Subscribed,
    Subscriptions,
    TerminalClient,
    TerminalUpdate,
    Tick,
    TradeUpdate,
    UnknownEvent,
    Unsubscribed,
)

__all__ = [
    "__version__",
    "Client",
    "AsyncClient",
    "TerminalClient",
    "AsyncTerminalClient",
    "AsyncStream",
    "Stream",
    "StreamEvent",
    "Tick",
    "Bar",
    "AccountUpdate",
    "PositionsUpdate",
    "TradeUpdate",
    "TerminalUpdate",
    "StreamWarning",
    "Subscribed",
    "Unsubscribed",
    "StreamErrorEvent",
    "Subscriptions",
    "UnknownEvent",
    "TradeEventData",
    "TerminalStatusData",
    "Account",
    "AccountSummary",
    "AccountInfo",
    "OpenedOrder",
    "HistoryTrade",
    "PositionTrade",
    "ServerTimezone",
    "Quote",
    "SymbolInfo",
    "Candle",
    "OrderResult",
    "MarginCalc",
    "ProfitCalc",
    "Health",
    "HealthChecks",
    "Platform",
    "TradingStatus",
    "OrderOperation",
    "OrderKind",
    "DealEntry",
    "HealthStatus",
    "Timeframe",
    "errors",
    "FxSocketError",
    "AuthError",
    "RateLimitError",
    "ValidationError",
    "NotFoundError",
    "AccountCapError",
    "NoSubscriptionError",
    "DuplicateAccountError",
    "ConnectFailedError",
    "TerminalNotReadyError",
    "TerminalTimeoutError",
    "UnsupportedOnPlatformError",
    "StreamError",
]
